#import <Foundation/Foundation.h>
#import "AGAdminUserUpdateDto.h"
#import "AGResultAdminUserResponseDto.h"
#import "AGResultObject.h"
#import "AGResultPageAdminUserResponseDto.h"
#import "AGResultVoid.h"
#import "AGApi.h"

/**
* Agri-Pest-Server API
* 农业病虫害识别 App 服务端 API 文档
*
* The version of the OpenAPI document: 1.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/



@interface AGAdminUserPanelApi: NSObject <AGApi>

extern NSString* kAGAdminUserPanelApiErrorDomain;
extern NSInteger kAGAdminUserPanelApiMissingParamErrorCode;

-(instancetype) initWithApiClient:(AGApiClient *)apiClient NS_DESIGNATED_INITIALIZER;

/// Create user
/// 
///
/// @param adminUserUpdateDto 
/// 
///  code:500 message:"Internal Server Error",
///  code:400 message:"Bad Request",
///  code:200 message:"OK"
///
/// @return AGResultAdminUserResponseDto*
-(NSURLSessionTask*) createUserWithAdminUserUpdateDto: (AGAdminUserUpdateDto*) adminUserUpdateDto
    completionHandler: (void (^)(AGResultAdminUserResponseDto* output, NSError* error)) handler;


/// Delete user
/// 
///
/// @param _id 
/// 
///  code:500 message:"Internal Server Error",
///  code:400 message:"Bad Request",
///  code:200 message:"OK"
///
/// @return AGResultVoid*
-(NSURLSessionTask*) deleteUserWithId: (NSNumber*) _id
    completionHandler: (void (^)(AGResultVoid* output, NSError* error)) handler;


/// Get user by ID
/// 
///
/// @param _id 
/// 
///  code:500 message:"Internal Server Error",
///  code:400 message:"Bad Request",
///  code:200 message:"OK"
///
/// @return AGResultAdminUserResponseDto*
-(NSURLSessionTask*) getUserByIdWithId: (NSNumber*) _id
    completionHandler: (void (^)(AGResultAdminUserResponseDto* output, NSError* error)) handler;


/// Get user list (Paginated)
/// 
///
/// @param page  (optional) (default to @0)
/// @param size  (optional) (default to @10)
/// 
///  code:500 message:"Internal Server Error",
///  code:400 message:"Bad Request",
///  code:200 message:"OK"
///
/// @return AGResultPageAdminUserResponseDto*
-(NSURLSessionTask*) getUsersWithPage: (NSNumber*) page
    size: (NSNumber*) size
    completionHandler: (void (^)(AGResultPageAdminUserResponseDto* output, NSError* error)) handler;


/// Update user
/// 
///
/// @param _id 
/// @param adminUserUpdateDto 
/// 
///  code:500 message:"Internal Server Error",
///  code:400 message:"Bad Request",
///  code:200 message:"OK"
///
/// @return AGResultAdminUserResponseDto*
-(NSURLSessionTask*) updateUserWithId: (NSNumber*) _id
    adminUserUpdateDto: (AGAdminUserUpdateDto*) adminUserUpdateDto
    completionHandler: (void (^)(AGResultAdminUserResponseDto* output, NSError* error)) handler;



@end
