#import <Foundation/Foundation.h>
#import "AGChangePhoneRequest.h"
#import "AGProfileUpdateRequest.h"
#import "AGResultListString.h"
#import "AGResultObject.h"
#import "AGResultString.h"
#import "AGResultUserProfileDto.h"
#import "AGResultVoid.h"
#import "AGApi.h"

/**
* Agri-Pest-Server API
* 农业病虫害识别 App 服务端 API 文档
*
* The version of the OpenAPI document: 1.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/



@interface AGApi: NSObject <AGApi>

extern NSString* kAGApiErrorDomain;
extern NSInteger kAGApiMissingParamErrorCode;

-(instancetype) initWithApiClient:(AGApiClient *)apiClient NS_DESIGNATED_INITIALIZER;

/// 
/// 
///
/// @param changePhoneRequest 
/// 
///  code:500 message:"Internal Server Error",
///  code:400 message:"Bad Request",
///  code:200 message:"OK"
///
/// @return AGResultVoid*
-(NSURLSessionTask*) changePhoneWithChangePhoneRequest: (AGChangePhoneRequest*) changePhoneRequest
    completionHandler: (void (^)(AGResultVoid* output, NSError* error)) handler;


/// 关注用户
/// 
///
/// @param _id 
/// 
///  code:500 message:"Internal Server Error",
///  code:400 message:"Bad Request",
///  code:200 message:"OK"
///
/// @return AGResultVoid*
-(NSURLSessionTask*) followUserWithId: (NSNumber*) _id
    completionHandler: (void (^)(AGResultVoid* output, NSError* error)) handler;


/// 获取当前用户资料
/// 
///
/// 
///  code:500 message:"Internal Server Error",
///  code:400 message:"Bad Request",
///  code:200 message:"OK"
///
/// @return AGResultUserProfileDto*
-(NSURLSessionTask*) getCurrentUserProfileWithCompletionHandler: 
    (void (^)(AGResultUserProfileDto* output, NSError* error)) handler;


/// 取消关注用户
/// 
///
/// @param _id 
/// 
///  code:500 message:"Internal Server Error",
///  code:400 message:"Bad Request",
///  code:200 message:"OK"
///
/// @return AGResultVoid*
-(NSURLSessionTask*) unfollowUserWithId: (NSNumber*) _id
    completionHandler: (void (^)(AGResultVoid* output, NSError* error)) handler;


/// 更新当前用户资料
/// 支持部分更新，字段为空则不修改
///
/// @param profileUpdateRequest 
/// 
///  code:500 message:"Internal Server Error",
///  code:400 message:"Bad Request",
///  code:200 message:"OK"
///
/// @return AGResultUserProfileDto*
-(NSURLSessionTask*) updateProfileWithProfileUpdateRequest: (AGProfileUpdateRequest*) profileUpdateRequest
    completionHandler: (void (^)(AGResultUserProfileDto* output, NSError* error)) handler;


/// 通用单文件上传
/// 上传单张图片/文件至对象存储，并返回可公开访问的 URL。
///
/// @param file 
/// @param prefix  (optional) (default to @"uploads/")
/// 
///  code:500 message:"Internal Server Error",
///  code:400 message:"Bad Request",
///  code:200 message:"OK"
///
/// @return AGResultString*
-(NSURLSessionTask*) uploadFileWithFile: (NSURL*) file
    prefix: (NSString*) prefix
    completionHandler: (void (^)(AGResultString* output, NSError* error)) handler;


/// 通用多文件批量上传
/// 一次性上传多张图片/文件，返回按顺序排列的 URL 列表。
///
/// @param files 
/// @param prefix  (optional) (default to @"uploads/")
/// 
///  code:500 message:"Internal Server Error",
///  code:400 message:"Bad Request",
///  code:200 message:"OK"
///
/// @return AGResultListString*
-(NSURLSessionTask*) uploadFilesWithFiles: (NSArray<NSURL*>*) files
    prefix: (NSString*) prefix
    completionHandler: (void (^)(AGResultListString* output, NSError* error)) handler;



@end
