#import <Foundation/Foundation.h>
#import "AGAdminUserUpdateDto.h"
#import "AGChangePhoneRequest.h"
#import "AGLoginRequest.h"
#import "AGProfileUpdateRequest.h"
#import "AGRefreshTokenRequest.h"
#import "AGRegisterRequest.h"
#import "AGResultAdminUserResponseDto.h"
#import "AGResultAuthResponse.h"
#import "AGResultListString.h"
#import "AGResultObject.h"
#import "AGResultPageAdminUserResponseDto.h"
#import "AGResultString.h"
#import "AGResultUserProfileDto.h"
#import "AGResultVoid.h"
#import "AGSendSmsRequest.h"
#import "AGSmsLoginRequest.h"
#import "AGApi.h"

/**
* Agri-Pest-Server API
* 农业病虫害识别 App 服务端 API 文档
*
* The version of the OpenAPI document: 1.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/



@interface AGApiService: NSObject <AGApi>

extern NSString* kAGApiServiceErrorDomain;
extern NSInteger kAGApiServiceMissingParamErrorCode;

-(instancetype) initWithApiClient:(AGApiClient *)apiClient NS_DESIGNATED_INITIALIZER;

/// 用户注册
/// 提供用户名、手机号和密码进行注册，注册成功后自动下发 JWT Token
///
/// @param registerRequest 
/// 
///  code:400 message:"Bad Request",
///  code:500 message:"Internal Server Error",
///  code:200 message:"OK"
///
/// @return AGResultAuthResponse*
-(NSURLSessionTask*) callRegisterWithRegisterRequest: (AGRegisterRequest*) registerRequest
    completionHandler: (void (^)(AGResultAuthResponse* output, NSError* error)) handler;


/// 换绑手机号
/// 
///
/// @param changePhoneRequest 
/// 
///  code:400 message:"Bad Request",
///  code:500 message:"Internal Server Error",
///  code:200 message:"OK"
///
/// @return AGResultVoid*
-(NSURLSessionTask*) changePhoneWithChangePhoneRequest: (AGChangePhoneRequest*) changePhoneRequest
    completionHandler: (void (^)(AGResultVoid* output, NSError* error)) handler;


/// 管理员创建用户
/// 
///
/// @param adminUserUpdateDto 
/// 
///  code:400 message:"Bad Request",
///  code:500 message:"Internal Server Error",
///  code:200 message:"OK"
///
/// @return AGResultAdminUserResponseDto*
-(NSURLSessionTask*) createUserWithAdminUserUpdateDto: (AGAdminUserUpdateDto*) adminUserUpdateDto
    completionHandler: (void (^)(AGResultAdminUserResponseDto* output, NSError* error)) handler;


/// 管理员删除用户
/// 
///
/// @param _id 
/// 
///  code:400 message:"Bad Request",
///  code:500 message:"Internal Server Error",
///  code:200 message:"OK"
///
/// @return AGResultVoid*
-(NSURLSessionTask*) deleteUserWithId: (NSNumber*) _id
    completionHandler: (void (^)(AGResultVoid* output, NSError* error)) handler;


/// 关注用户
/// 
///
/// @param _id 
/// 
///  code:400 message:"Bad Request",
///  code:500 message:"Internal Server Error",
///  code:200 message:"OK"
///
/// @return AGResultVoid*
-(NSURLSessionTask*) followUserWithId: (NSNumber*) _id
    completionHandler: (void (^)(AGResultVoid* output, NSError* error)) handler;


/// 获取当前用户资料
/// 
///
/// 
///  code:400 message:"Bad Request",
///  code:500 message:"Internal Server Error",
///  code:200 message:"OK"
///
/// @return AGResultUserProfileDto*
-(NSURLSessionTask*) getCurrentUserProfileWithCompletionHandler: 
    (void (^)(AGResultUserProfileDto* output, NSError* error)) handler;


/// 获取指定用户详情
/// 
///
/// @param _id 
/// 
///  code:400 message:"Bad Request",
///  code:500 message:"Internal Server Error",
///  code:200 message:"OK"
///
/// @return AGResultAdminUserResponseDto*
-(NSURLSessionTask*) getUserByIdWithId: (NSNumber*) _id
    completionHandler: (void (^)(AGResultAdminUserResponseDto* output, NSError* error)) handler;


/// 获取用户列表 (分页)
/// 
///
/// @param page  (optional) (default to @0)
/// @param size  (optional) (default to @10)
/// 
///  code:400 message:"Bad Request",
///  code:500 message:"Internal Server Error",
///  code:200 message:"OK"
///
/// @return AGResultPageAdminUserResponseDto*
-(NSURLSessionTask*) getUsersWithPage: (NSNumber*) page
    size: (NSNumber*) size
    completionHandler: (void (^)(AGResultPageAdminUserResponseDto* output, NSError* error)) handler;


/// 健康检查
/// 
///
/// 
///  code:400 message:"Bad Request",
///  code:500 message:"Internal Server Error",
///  code:200 message:"OK"
///
/// @return AGResultString*
-(NSURLSessionTask*) healthWithCompletionHandler: 
    (void (^)(AGResultString* output, NSError* error)) handler;


/// 用户登录
/// 使用用户名或手机号加上密码进行登录，成功后返回 JWT Token
///
/// @param loginRequest 
/// 
///  code:400 message:"Bad Request",
///  code:500 message:"Internal Server Error",
///  code:200 message:"OK"
///
/// @return AGResultAuthResponse*
-(NSURLSessionTask*) loginWithLoginRequest: (AGLoginRequest*) loginRequest
    completionHandler: (void (^)(AGResultAuthResponse* output, NSError* error)) handler;


/// 手机号验证码登录
/// 使用手机号和验证码进行登录，如果手机号未注册将自动注册
///
/// @param smsLoginRequest 
/// 
///  code:400 message:"Bad Request",
///  code:500 message:"Internal Server Error",
///  code:200 message:"OK"
///
/// @return AGResultAuthResponse*
-(NSURLSessionTask*) loginBySmsWithSmsLoginRequest: (AGSmsLoginRequest*) smsLoginRequest
    completionHandler: (void (^)(AGResultAuthResponse* output, NSError* error)) handler;


/// 刷新 Token
/// 使用有效的 Refresh Token 获取新的 Access Token
///
/// @param refreshTokenRequest 
/// 
///  code:400 message:"Bad Request",
///  code:500 message:"Internal Server Error",
///  code:200 message:"OK"
///
/// @return AGResultAuthResponse*
-(NSURLSessionTask*) refreshWithRefreshTokenRequest: (AGRefreshTokenRequest*) refreshTokenRequest
    completionHandler: (void (^)(AGResultAuthResponse* output, NSError* error)) handler;


/// 发送短信验证码
/// 使用阿里云短信认证服务发送验证码（如果未配置AK，则使用模拟发送并在控制台打印）
///
/// @param sendSmsRequest 
/// 
///  code:400 message:"Bad Request",
///  code:500 message:"Internal Server Error",
///  code:200 message:"OK"
///
/// @return AGResultVoid*
-(NSURLSessionTask*) sendSmsCodeWithSendSmsRequest: (AGSendSmsRequest*) sendSmsRequest
    completionHandler: (void (^)(AGResultVoid* output, NSError* error)) handler;


/// 取消关注用户
/// 
///
/// @param _id 
/// 
///  code:400 message:"Bad Request",
///  code:500 message:"Internal Server Error",
///  code:200 message:"OK"
///
/// @return AGResultVoid*
-(NSURLSessionTask*) unfollowUserWithId: (NSNumber*) _id
    completionHandler: (void (^)(AGResultVoid* output, NSError* error)) handler;


/// 更新当前用户资料
/// 支持部分更新，字段为空则不修改
///
/// @param profileUpdateRequest 
/// 
///  code:400 message:"Bad Request",
///  code:500 message:"Internal Server Error",
///  code:200 message:"OK"
///
/// @return AGResultUserProfileDto*
-(NSURLSessionTask*) updateProfileWithProfileUpdateRequest: (AGProfileUpdateRequest*) profileUpdateRequest
    completionHandler: (void (^)(AGResultUserProfileDto* output, NSError* error)) handler;


/// 管理员更新用户
/// 
///
/// @param _id 
/// @param adminUserUpdateDto 
/// 
///  code:400 message:"Bad Request",
///  code:500 message:"Internal Server Error",
///  code:200 message:"OK"
///
/// @return AGResultAdminUserResponseDto*
-(NSURLSessionTask*) updateUserWithId: (NSNumber*) _id
    adminUserUpdateDto: (AGAdminUserUpdateDto*) adminUserUpdateDto
    completionHandler: (void (^)(AGResultAdminUserResponseDto* output, NSError* error)) handler;


/// 通用单文件上传
/// 上传单张图片/文件至对象存储，并返回可公开访问的 URL。
///
/// @param file 
/// @param prefix  (optional) (default to @"uploads/")
/// 
///  code:400 message:"Bad Request",
///  code:500 message:"Internal Server Error",
///  code:200 message:"OK"
///
/// @return AGResultString*
-(NSURLSessionTask*) uploadFileWithFile: (NSURL*) file
    prefix: (NSString*) prefix
    completionHandler: (void (^)(AGResultString* output, NSError* error)) handler;


/// 通用多文件批量上传
/// 一次性上传多张图片/文件，返回按顺序排列的 URL 列表。
///
/// @param files 
/// @param prefix  (optional) (default to @"uploads/")
/// 
///  code:400 message:"Bad Request",
///  code:500 message:"Internal Server Error",
///  code:200 message:"OK"
///
/// @return AGResultListString*
-(NSURLSessionTask*) uploadFilesWithFiles: (NSArray<NSURL*>*) files
    prefix: (NSString*) prefix
    completionHandler: (void (^)(AGResultListString* output, NSError* error)) handler;



@end
