#import <Foundation/Foundation.h>
#import "AGLoginRequest.h"
#import "AGRefreshTokenRequest.h"
#import "AGRegisterRequest.h"
#import "AGResultAuthResponse.h"
#import "AGResultObject.h"
#import "AGResultVoid.h"
#import "AGSendSmsRequest.h"
#import "AGSmsLoginRequest.h"
#import "AGApi.h"

/**
* Agri-Pest-Server API
* 农业病虫害识别 App 服务端 API 文档
*
* The version of the OpenAPI document: 1.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/



@interface AGAuthenticationApi: NSObject <AGApi>

extern NSString* kAGAuthenticationApiErrorDomain;
extern NSInteger kAGAuthenticationApiMissingParamErrorCode;

-(instancetype) initWithApiClient:(AGApiClient *)apiClient NS_DESIGNATED_INITIALIZER;

/// 用户注册
/// 提供用户名、手机号和密码进行注册，注册成功后自动下发 JWT Token
///
/// @param registerRequest 
/// 
///  code:500 message:"Internal Server Error",
///  code:400 message:"Bad Request",
///  code:200 message:"OK"
///
/// @return AGResultAuthResponse*
-(NSURLSessionTask*) callRegisterWithRegisterRequest: (AGRegisterRequest*) registerRequest
    completionHandler: (void (^)(AGResultAuthResponse* output, NSError* error)) handler;


/// 用户登录
/// 使用用户名或手机号加上密码进行登录，成功后返回 JWT Token
///
/// @param loginRequest 
/// 
///  code:500 message:"Internal Server Error",
///  code:400 message:"Bad Request",
///  code:200 message:"OK"
///
/// @return AGResultAuthResponse*
-(NSURLSessionTask*) loginWithLoginRequest: (AGLoginRequest*) loginRequest
    completionHandler: (void (^)(AGResultAuthResponse* output, NSError* error)) handler;


/// 手机号验证码登录
/// 使用手机号和验证码进行登录，如果手机号未注册将自动注册
///
/// @param smsLoginRequest 
/// 
///  code:500 message:"Internal Server Error",
///  code:400 message:"Bad Request",
///  code:200 message:"OK"
///
/// @return AGResultAuthResponse*
-(NSURLSessionTask*) loginBySmsWithSmsLoginRequest: (AGSmsLoginRequest*) smsLoginRequest
    completionHandler: (void (^)(AGResultAuthResponse* output, NSError* error)) handler;


/// 刷新 Token
/// 使用有效的 Refresh Token 获取新的 Access Token
///
/// @param refreshTokenRequest 
/// 
///  code:500 message:"Internal Server Error",
///  code:400 message:"Bad Request",
///  code:200 message:"OK"
///
/// @return AGResultAuthResponse*
-(NSURLSessionTask*) refreshWithRefreshTokenRequest: (AGRefreshTokenRequest*) refreshTokenRequest
    completionHandler: (void (^)(AGResultAuthResponse* output, NSError* error)) handler;


/// 发送短信验证码
/// 使用阿里云短信认证服务发送验证码（如果未配置AK，则使用模拟发送并在控制台打印）
///
/// @param sendSmsRequest 
/// 
///  code:500 message:"Internal Server Error",
///  code:400 message:"Bad Request",
///  code:200 message:"OK"
///
/// @return AGResultVoid*
-(NSURLSessionTask*) sendSmsCodeWithSendSmsRequest: (AGSendSmsRequest*) sendSmsRequest
    completionHandler: (void (^)(AGResultVoid* output, NSError* error)) handler;



@end
