#import <Foundation/Foundation.h>
#import "AGResultObject.h"
#import "AGResultString.h"
#import "AGApi.h"

/**
* Agri-Pest-Server API
* 农业病虫害识别 App 服务端 API 文档
*
* The version of the OpenAPI document: 1.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/



@interface AGSystemHealthApi: NSObject <AGApi>

extern NSString* kAGSystemHealthApiErrorDomain;
extern NSInteger kAGSystemHealthApiMissingParamErrorCode;

-(instancetype) initWithApiClient:(AGApiClient *)apiClient NS_DESIGNATED_INITIALIZER;

/// 健康检查
/// 
///
/// 
///  code:500 message:"Internal Server Error",
///  code:400 message:"Bad Request",
///  code:200 message:"OK"
///
/// @return AGResultString*
-(NSURLSessionTask*) healthWithCompletionHandler: 
    (void (^)(AGResultString* output, NSError* error)) handler;



@end
