#import <Foundation/Foundation.h>
#import "AGObject.h"

/**
* Agri-Pest-Server API
* 农业病虫害识别 App 服务端 API 文档
*
* The version of the OpenAPI document: 1.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/





@protocol AGAdminUserResponseDto
@end

@interface AGAdminUserResponseDto : AGObject


@property(nonatomic) NSNumber* _id;

@property(nonatomic) NSString* username;

@property(nonatomic) NSString* phone;

@property(nonatomic) NSString* role;

@property(nonatomic) NSDate* createdAt;

@property(nonatomic) NSString* fullName;

@property(nonatomic) NSString* avatarUrl;

@property(nonatomic) NSString* bio;

@property(nonatomic) NSString* location;

@property(nonatomic) NSString* followedCrops;

@end
