#import <Foundation/Foundation.h>
#import "AGObject.h"

/**
* Agri-Pest-Server API
* 农业病虫害识别 App 服务端 API 文档
*
* The version of the OpenAPI document: 1.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/


#import "AGPageableObject.h"
#import "AGPostResponseDto.h"
#import "AGSortObject.h"
@protocol AGPageableObject;
@class AGPageableObject;
@protocol AGPostResponseDto;
@class AGPostResponseDto;
@protocol AGSortObject;
@class AGSortObject;



@protocol AGPagePostResponseDto
@end

@interface AGPagePostResponseDto : AGObject


@property(nonatomic) NSNumber* totalPages;

@property(nonatomic) NSNumber* totalElements;

@property(nonatomic) NSNumber* first;

@property(nonatomic) NSNumber* last;

@property(nonatomic) AGSortObject* sort;

@property(nonatomic) NSNumber* numberOfElements;

@property(nonatomic) AGPageableObject* pageable;

@property(nonatomic) NSNumber* number;

@property(nonatomic) NSNumber* size;

@property(nonatomic) NSArray<AGPostResponseDto>* content;

@property(nonatomic) NSNumber* empty;

@end
