#import <Foundation/Foundation.h>
#import "AGObject.h"

/**
* Agri-Pest-Server API
* 农业病虫害识别 App 服务端 API 文档
*
* The version of the OpenAPI document: 1.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/


#import "AGUserProfileDto.h"
@protocol AGUserProfileDto;
@class AGUserProfileDto;



@protocol AGResultUserProfileDto
@end

@interface AGResultUserProfileDto : AGObject


@property(nonatomic) NSNumber* code;

@property(nonatomic) NSString* message;

@property(nonatomic) AGUserProfileDto* data;

@end
