#import <Foundation/Foundation.h>
#import "AGObject.h"

/**
* Agri-Pest-Server API
* 农业病虫害识别 App 服务端 API 文档
*
* The version of the OpenAPI document: 1.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/





@protocol AGTagOperationRequest
@end

@interface AGTagOperationRequest : AGObject

/* 打卡日期 [optional]
 */
@property(nonatomic) NSDate* recordDate;
/* 标签类型: WATERING, FERTILIZING, MEDICATION, NOTE [optional]
 */
@property(nonatomic) NSString* tagType;
/* 笔记内容 (仅在 tagType 为 NOTE 时有效) [optional]
 */
@property(nonatomic) NSString* content;

@end
